disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - identifier_name
  - line_length
  - comment_spacing
  - non_optional_string_data_conversion
  - multiple_closures_with_trailing_closure
  - static_over_final_class
  - identifier_name
  - line_length

opt_in_rules:
  - empty_count
  - force_unwrapping

excluded:
  - Pods
  - DerivedData
  - .build

identifier_name:
  excluded:
    - _content
    - safety_level
    - path_alias
